service: gointensive

frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  zapgpt:
    handler: bin/zapgpt
    events:
      - httpApi:
          path: /
          method: post

